"""Local CLI debug entry for the H5 offline-app lane.

Mirrors MCP tools ``kb_create_app`` / ``kb_list_apps`` / ``kb_delete_app`` so
apps can be managed without starting the MCP server.

Examples (PowerShell):

    python -m tools.app list
    python -m tools.app create demo
    python -m tools.app create dashboard --files-json .\app-files.json --overwrite
    python -m tools.app url demo
    python -m tools.app delete demo
    python -m tools.app rebuild-index
"""

from __future__ import annotations

import json
from pathlib import Path

import click

from services import apps as apps_svc
from services.config import load_config


def _emit(payload: dict) -> None:
    click.echo(json.dumps(payload, ensure_ascii=False, indent=2, default=str))


def _default_files(slug: str, title: str | None = None) -> dict[str, str]:
    safe_title = title or f"{slug} app"
    return {
        "index.html": (
            "<!doctype html>\n"
            "<html lang=\"zh-CN\">\n"
            "  <head>\n"
            "    <meta charset=\"utf-8\" />\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
            f"    <title>{safe_title}</title>\n"
            "    <link rel=\"stylesheet\" href=\"style.css\" />\n"
            "  </head>\n"
            "  <body>\n"
            "    <main class=\"app\">\n"
            f"      <h1>{safe_title}</h1>\n"
            "      <p>Offline app scaffold generated by tools.app.</p>\n"
            "      <button id=\"ping\" type=\"button\">Click me</button>\n"
            "      <pre id=\"out\" aria-live=\"polite\"></pre>\n"
            "    </main>\n"
            "    <script src=\"app.js\"></script>\n"
            "  </body>\n"
            "</html>\n"
        ),
        "style.css": (
            ":root {\n"
            "  color-scheme: light;\n"
            "  --bg: #f5f7fb;\n"
            "  --card: #ffffff;\n"
            "  --text: #1c2333;\n"
            "  --accent: #0a7f5a;\n"
            "}\n\n"
            "body {\n"
            "  margin: 0;\n"
            "  font-family: Segoe UI, PingFang SC, Microsoft YaHei, sans-serif;\n"
            "  background: linear-gradient(160deg, #eef6ff, var(--bg));\n"
            "  color: var(--text);\n"
            "}\n\n"
            ".app {\n"
            "  max-width: 680px;\n"
            "  margin: 48px auto;\n"
            "  padding: 24px;\n"
            "  background: var(--card);\n"
            "  border-radius: 16px;\n"
            "  box-shadow: 0 14px 40px rgba(0, 0, 0, 0.08);\n"
            "}\n\n"
            "button {\n"
            "  border: 0;\n"
            "  border-radius: 10px;\n"
            "  padding: 10px 14px;\n"
            "  background: var(--accent);\n"
            "  color: #fff;\n"
            "  cursor: pointer;\n"
            "}\n"
        ),
        "app.js": (
            "const out = document.getElementById('out');\n"
            "const btn = document.getElementById('ping');\n"
            "if (btn && out) {\n"
            "  btn.addEventListener('click', () => {\n"
            "    out.textContent = `OK at ${new Date().toLocaleString()}`;\n"
            "  });\n"
            "}\n"
        ),
    }


@click.group()
@click.option("--config", "config_path", type=click.Path(path_type=Path), default=None)
@click.option("--kb-root", "kb_root", type=str, default=None)
@click.pass_context
def main(ctx: click.Context, config_path: Path | None, kb_root: str | None) -> None:
    """Knowledge base H5 apps maintenance commands."""
    ctx.ensure_object(dict)
    ctx.obj["cfg"] = load_config(config_path=config_path, knowledge_base_root_override=kb_root)


@main.command("list")
@click.pass_context
def list_apps(ctx: click.Context) -> None:
    """List all apps under <kb_root>/apps."""
    cfg = ctx.obj["cfg"]
    apps = apps_svc.list_apps(cfg)
    _emit({"apps": apps, "count": len(apps)})


@main.command("url")
@click.argument("slug")
@click.pass_context
def app_url(ctx: click.Context, slug: str) -> None:
    """Print resolved local URL for one app slug."""
    cfg = ctx.obj["cfg"]
    slug = apps_svc.validate_slug(slug)
    target = apps_svc.app_dir(cfg, slug)
    _emit(
        {
            "slug": slug,
            "path": str(target),
            "url": apps_svc.app_url(cfg, slug),
            "exists": target.exists(),
        }
    )


@main.command("create")
@click.argument("slug")
@click.option("--overwrite", is_flag=True, help="Overwrite when app slug already exists.")
@click.option("--files-json", type=click.Path(path_type=Path, exists=True), default=None,
              help="JSON file: {\"rel/path\": \"content\", ...}")
@click.option("--title", default=None, help="Title used by default scaffold files.")
@click.option("--no-default", is_flag=True,
              help="Disable default scaffold files; requires --files-json.")
@click.pass_context
def create_app(
    ctx: click.Context,
    slug: str,
    overwrite: bool,
    files_json: Path | None,
    title: str | None,
    no_default: bool,
) -> None:
    """Create one app under <kb_root>/apps/<slug>."""
    cfg = ctx.obj["cfg"]

    files: dict[str, str] = {}
    if not no_default:
        files.update(_default_files(slug, title=title))

    if files_json is not None:
        raw = json.loads(files_json.read_text(encoding="utf-8"))
        if not isinstance(raw, dict):
            raise click.BadParameter("--files-json must contain a JSON object")
        for k, v in raw.items():
            if not isinstance(k, str) or not isinstance(v, str):
                raise click.BadParameter("--files-json entries must be string:string")
        files.update(raw)

    if not files:
        raise click.BadParameter("no files to write; provide --files-json or remove --no-default")

    result = apps_svc.create_app(cfg, slug, files, overwrite=overwrite, title=title)
    _emit(result.to_dict())


@main.command("delete")
@click.argument("slug")
@click.option("--yes", "-y", is_flag=True, help="Skip interactive confirmation.")
@click.pass_context
def delete_app(ctx: click.Context, slug: str, yes: bool) -> None:
    """Delete an app directory and drop it from index.json."""
    cfg = ctx.obj["cfg"]
    slug = apps_svc.validate_slug(slug)
    if not yes:
        target = apps_svc.app_dir(cfg, slug)
        click.confirm(f"Delete app {slug!r} at {target}?", abort=True)
    _emit(apps_svc.delete_app(cfg, slug))


@main.command("rebuild-index")
@click.pass_context
def rebuild_index(ctx: click.Context) -> None:
    """Rescan apps_dir and regenerate index.json / index.html."""
    cfg = ctx.obj["cfg"]
    _emit(apps_svc.rebuild_index(cfg))


if __name__ == "__main__":
    main()
